### ISSUE TITLE
createContext error

### ISSUE THREAD

**Issue by mariacheline** [marciobarrios/react-intl-number-format#1]
Hi, I've copied the example but I'm getting the following error:

```
./node_modules/react-intl-number-format/dist/index.mjs
Can't import the named export 'createContext' from non EcmaScript module (only default export is available)
```

any ideas?

**Comment by marciobarrios** [comment]
Hi @mariacheline I will check it out today! Thanks for reporting it. 
Would be nice if you create a CodeSandbox to reproduce the error!

**Comment by marciobarrios** [comment]
It's strange because `createContext` should be imported from React, do you have React installed right?

In this CodeSandbox (the one liked from the README), the Provider is working: https://codesandbox.io/s/react-intl-number-format-u1rt3

Can you show me how are you setting up the provider? Thanks

**Comment by mariacheline** [comment]
Thanks! Apparently I missed the Provider part.

**Comment by cmnstmntmn** [comment]
same error with CRA, using the provider is not solving the issue.

**Comment by marciobarrios** [comment]
@cmnstmntmn can you reproduce it in a Codesandbox?

**Comment by cmnstmntmn** [comment]
can't reproduce it.

hoever i'm using it this way for now.

`import { Number } from "react-intl-number-format/dist/index.js";`

if this might help you https://github.com/facebook/create-react-app/issues/3237#issuecomment-354554624

**Comment by davemecha** [comment]
> can't reproduce it.
> 
> hoever i'm using it this way for now.
> 
> `import { Number } from "react-intl-number-format/dist/index.js";`
> 
> if this might help you [facebook/create-react-app#3237 (comment)](https://github.com/facebook/create-react-app/issues/3237#issuecomment-354554624)

Thanks for this workaround. I was able to use the provider with this import as well.

```tsx
import { IntlProvider } from 'react-intl-number-format/dist/index.js';

[...]

  <IntlProvider config={ intlConfig }>
    { children }
  </IntlProvider>

[...]
```

and

```tsx
import { Currency } from 'react-intl-number-format/dist/index.js';

[...]

  <Currency>{ price }</Currency>

[...]
```
